Conflict between aioflask and other requirements
Performing pip install -r requirement.txt produces the following error in development mode:

```
ERROR: Cannot install Flask==1.1.1 and -r requirement.txt (line 9) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Flask==1.1.1
    aioflask 0.4.0 depends on flask>=2
```
```
ERROR: Cannot install Jinja2==2.10.3, aioflask, Jinja2==2.10.3, aioflask, Jinja2==2.10.3, aioflask, Werkzeug==0.16.0, aioflask, Werkzeug==0.16.0, aioflask, Werkzeug==0.16.0, aioflask, Werkzeug==0.16.0 and aioflask because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Jinja2==2.10.3
    flask 2.1.2 depends on Jinja2>=3.0
    The user requested Jinja2==2.10.3
    flask 2.1.1 depends on Jinja2>=3.0
    The user requested Jinja2==2.10.3
    flask 2.1.0 depends on Jinja2>=3.0
    The user requested Werkzeug==0.16.0
    flask 2.0.3 depends on Werkzeug>=2.0
    The user requested Werkzeug==0.16.0
    flask 2.0.2 depends on Werkzeug>=2.0
    The user requested Werkzeug==0.16.0
    flask 2.0.1 depends on Werkzeug>=2.0
    The user requested Werkzeug==0.16.0
    flask 2.0.0 depends on Werkzeug>=2.0
```
The package aioflask itself covers the dependencies - Jninja2, itsdangerous, Werkzeug, MarkupSafe, click, flask. So we can remove them from requirement.txt